### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'external/weights/osnet_ain_ms_d_c.pth.tar'

### ISSUE THREAD

**Issue by rxmao** [GerardMaggiolino/Deep-OC-SORT#2]
Thank you  for your great work! When I run the code, I met this problem.

**Comment by GerardMaggiolino** [comment]
Hey, thanks for your interest! This is because the model weights for the reid model we use for MOT17/20 half-val aren’t uploaded. 

We use different embedding models for MOT val / test since validation is just half of the training set. If we used the reid model trained on the training set, we get basically 100% accuracy on half-val. 

Sorry for the delay, I’ll upload all the model weights for all reid models and detectors on or before this weekend, 03/04/23. Keeping this issue open until I do so.

**Comment by YanhuiS** [comment]
Wait for a reply.

**Comment by GerardMaggiolino** [comment]
Sorry for the delay, I've updated the README and ironed out the requirements. Can you try running it now? You should be able to follow straight down the README to generate both baseline and best validation results.

**Comment by goldentimecoolk** [comment]
@GerardMaggiolino Hi, I want to change the detector to dabdetr to do inference and the reid model may remain the same. Is it convenient to share the ReID model trained on dancetrack (dance_sbs_S50.pth)?
