### ISSUE TITLE
the results of MOT20 val

### ISSUE THREAD

**Issue by piggi999** [GerardMaggiolino/Deep-OC-SORT#9]
I have a question, why the test size of MOT20 test is differernt from the other datasets?

**Comment by GerardMaggiolino** [comment]
Following OC-SORT, we use a larger MOT20 image size as its sequences have significantly more and smaller bounding boxes. 

It's an (imo unfortunately) standard procedure in the MOT community to tune based on the dataset. For example, [you'll see that BoT-SORT tunes not only image size in the YOLOX configs](https://github.com/NirAharon/BoT-SORT/blob/251985436d6712aaf682aaaf5f71edb4987224bd/tools/track.py#L322), but also track buffers and track thresholds on a _per-sequence basis_ , with different [cost matrix algorithms](https://github.com/NirAharon/BoT-SORT/blob/251985436d6712aaf682aaaf5f71edb4987224bd/tracker/bot_sort.py#L307) depending on the dataset. 

We keep our algorithms consistent between all three datasets with the same thresholds unless otherwise specified.

**Comment by piggi999** [comment]
Get it! I have another question about MOT challenge. I wonder if you can help me. I just submitted a result of MOT17, but it emailed me twice and added two submission number. My email is yanhuis1999@mail.ustc.edu.cn.

**Comment by GerardMaggiolino** [comment]
Sorry, I'm not too familiar with this. You may have better luck emailing the MOT team. Best of luck with your research!

**Comment by piggi999** [comment]
Ok, thanks you!
